#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by summarize_elder_v2_results.py
# Independent best checkpoints by validation task_score=(F1+Kappa+CCC)/3.

STRICT_LOAD=1 \
TRACK=Track1 \
SUBTRACK="A-V-G+P" \
OUTPUT_DIR="blind_submission/Track1/A_V_G_P_elder_v2_selected" \
BINARY_CKPT="checkpoints_elder_v2/Track1/A-V-G+P/binary/elder_v2_binary_A_V_G_P_hybrid_attn_wav2vec_resnet_h64_s3407/best_model_2026-05-10-04.57.07.pth" \
TERNARY_CKPT="checkpoints_elder_v2/Track1/A-V-G+P/ternary/elder_v2_ternary_A_V_G_P_hybrid_attn_wav2vec_resnet_h64_s2025/best_model_2026-05-10-06.07.23.pth" \
bash scripts/run_blind_depformer_submission.sh
